baseURL = "https://example.org/"
languageCode = "en-us"
title = "Boxup Crime London"
theme = "navigator-hugo"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = true
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
    logo = "images/client-logo/logo-2.png"

    [[Params.listeLangues]]
    code = "en"

[Languages]

    ############# Main Site
    [Languages.en]
    weight = 2
    languageCode = "en-us"
    title = "BOXUP CRIME - FOR YOUNG PEOPLE"
    dateFormat = "January 2, 2006"

    home = "Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "ENGLISH Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
    footerServiceTitle = "ENGLISH Service"
    footerQuicklinkTitle = "ENGLISH Quicklinks"
    footerAboutTitle = "ENGLISH About"
    footerSubscribeTitle = "ENGLISH Subscribe"

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "FREEING YOUNG PEOPLE"
        description = "We are passionate about getting 1000s of young people out of gangs each year"
        button  = true
        btnText = "Know More"
        btnURL  = "about"
        videoThumb = "images/boxup-logo.png"
        videoURL   = "https://www.youtube.com/embed/6A_TyAMSG40"

    # About 2 Section
    [Languages.en.params.aboutSm]
        enable  = true
        title   = "ENGLISH We have explored the digital landscape with passion for a long time"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = true
        topTitle= "OUR UNTOLD STORY"
        title   = "ENGLISH Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "Contact Us"
        title   = "Where are we"
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        address = "59 Grosvenor Road, Dagenham, Essex, RM8 1NL"
        phone   = "07504628848"
        fax     = "0208 517 4446"
        facebook= "https://en-gb.facebook.com/boxupcrimeuk/"
        twitter = "https://twitter.com/boxupcrime?lang=en"
        instagram= "https://www.instagram.com/boxupcrime/"
        mapLatitude = "51.56467869999999"
        mapLongitude= "0.1469876999999542"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "ENGLISH Let's Create Something Together"
        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "portfolio"
        url     = "portfolio"
        weight  = 4
    [[menu.nav]]
        name    = "blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 6

    # Footer Service Menu
    [[menu.service]]
        name    = "graphicdesign"
        url     = "service"
        weight  = 1
    [[menu.service]]
        name    = "webdesign"
        url     = "service"
        weight  = 2
    [[menu.service]]
        name    = "webdevelopment"
        url     = "service"
        weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "partners"
        url     = "about"
        weight  = 1
    [[menu.quicklink]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.quicklink]]
        name    = "faqs"
        url     = "about"
        weight  = 3
    [[menu.quicklink]]
        name    = "badges"
        url     = "about"
        weight  = 4
